# Generated by Django 4.2.9 on 2024-02-05 03:40

import django.core.validators
from django.db import migrations, models
import facerec.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.IntegerField()),
                ('nome_completo', models.CharField(max_length=200)),
                ('similaridade', models.FloatField(default=0.0)),
                ('ip', models.GenericIPAddressField()),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
