# Generated by Django 4.2.9 on 2024-02-05 04:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import facerec.models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default='', max_length=200)),
                ('port', models.IntegerField(default=8000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('semestre_atual', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8'), (9, 'Semestre 9'), (10, 'Semestre 10'), (11, 'Semestre 11'), (12, 'Semestre 12'), (13, 'Semestre 13'), (14, 'Semestre 14'), (15, 'Semestre 15')], default=1)),
                ('foto', models.ImageField(blank=True, upload_to=facerec.models.image_full_path)),
            ],
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data_hora',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
